### ISSUE TITLE
Change the letter used to describe a mode

### ISSUE THREAD

**Issue by Eloquencere** [ndavd/zellij-cb#1]
I like the approach of zellij-cb but I don't think associating a letter with a mode satisfies everyone, I have a list of nerd-font icons that could be used to represent different modes so, it would be great if that configuration existed

Plus, the existing icons to indicate sync, zoomed tab etc are pretty bad and I have a few emojis that could be used there as well, so, an inclusion of such an option would also be greatly appreciated

**Comment by Eloquencere** [comment]
Also, it's not very evident how to convert the source code to a wasm, would be great if you had releases for that

**Comment by ndavd** [comment]
> I like the approach of zellij-cb but I don't think associating a letter with a mode satisfies everyone, I have a list of nerd-font icons that could be used to represent different modes so, it would be great if that configuration existed

Thanks for the issue, I'll add the option to set a custom string for the mode.

> Plus, the existing icons to indicate sync, zoomed tab etc are pretty bad

I don't use those features and I'm not sure how they look like, so for now it's not planned. I'm open to pull requests or explain the feature a bit better so I can see how easily it can be integrated and I'll add it once I find some time.

> Also, it's not very evident how to convert the source code to a wasm, would be great if you had releases for that

I'll add releases in the future but for now you can refer to the installation section in the README: https://github.com/ndavd/zellij-cb#installation.

**Comment by ndavd** [comment]
Added configuration option for mode label override (Check it [here](https://github.com/ndavd/zellij-cb?tab=readme-ov-file#available-configuration)). Now you should be able to alter the label of any mode you want. Let me know if this solves your issue.

**Comment by Eloquencere** [comment]
Hey @ndavd thanks a lot for considering my issue, it'll be a while until I get back to you with a comment, as my circumstances currently don't require facing a terminal prompt. When I do get back around, I'll be sure to update you.
